project:
  type: website

website:
  title: "blogup"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
    left:
      - prose.qmd
format:
  html:
    theme: cosmo
    css: styles.css
